### ISSUE TITLE
Support for docking branch colors?

### ISSUE THREAD

**Issue by rewrking** [Patitotective/ImThemes#19]
I was trying this out and noticed it doesn't have the two docking branch colors. Any plans to add them?

```cpp
ImGuiCol_DockingPreview,  // 38
ImGuiCol_DockingEmptyBg,  // 39
```

**Comment by Patitotective** [comment]
This is because this application is written in Nim, and the bindings for Dear ImGui in Nim do not support the docking branch.
It could be possible to add those colors but you wouldn't able to preview them, so I'm not sure if it's worth adding them.

**Comment by rewrking** [comment]
Ah, makes sense. Thanks!
