### ISSUE TITLE
[Theme] Modern

### ISSUE THREAD

**Issue by LousyBook-01** [Patitotective/ImThemes#32]
[[themes]]
name = "Modern"
author = "LousyBook01"
description = "cool theme i made, this is meant to look like the modern flat ui"
tags = ["dark", "rounded", "red", "orange", "pink", "gray", "magenta"]
date = "pr-merge-date"
[themes.style]
alpha = 1.0
disabledAlpha = 0.300000011920929
windowPadding = [10.10000038146973, 10.10000038146973]
windowRounding = 10.30000019073486
windowBorderSize = 1.0
windowMinSize = [20.0, 32.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "Right"
childRounding = 8.199999809265137
childBorderSize = 1.0
popupRounding = 10.69999980926514
popupBorderSize = 1.0
framePadding = [20.0, 1.5]
frameRounding = 4.800000190734863
frameBorderSize = 0.0
itemSpacing = [9.699999809265137, 5.300000190734863]
itemInnerSpacing = [5.400000095367432, 9.300000190734863]
cellPadding = [7.900000095367432, 2.0]
indentSpacing = 10.69999980926514
columnsMinSpacing = 6.0
scrollbarSize = 12.10000038146973
scrollbarRounding = 20.0
grabMinSize = 10.0
grabRounding = 4.599999904632568
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]
[themes.style.colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(255, 255, 255, 0.3991416096687317)"
WindowBg = "rgba(10, 10, 10, 0.9399999976158142)"
ChildBg = "rgba(0, 0, 0, 0.0)"
PopupBg = "rgba(13, 13, 13, 0.9399999976158142)"
Border = "rgba(109, 109, 127, 0.5)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(0, 0, 0, 0.4206008315086365)"
FrameBgHovered = "rgba(36, 36, 36, 0.4000000059604645)"
FrameBgActive = "rgba(59, 59, 59, 0.8626609444618225)"
TitleBg = "rgba(0, 0, 0, 1.0)"
TitleBgActive = "rgba(24, 24, 24, 1.0)"
TitleBgCollapsed = "rgba(0, 0, 0, 0.2918455004692078)"
MenuBarBg = "rgba(35, 35, 35, 1.0)"
ScrollbarBg = "rgba(5, 5, 5, 0.5299999713897705)"
ScrollbarGrab = "rgba(79, 79, 79, 1.0)"
ScrollbarGrabHovered = "rgba(104, 104, 104, 1.0)"
ScrollbarGrabActive = "rgba(130, 130, 130, 1.0)"
CheckMark = "rgba(250, 66, 66, 1.0)"
SliderGrab = "rgba(255, 255, 255, 1.0)"
SliderGrabActive = "rgba(66, 150, 250, 1.0)"
Button = "rgba(0, 0, 0, 0.5793991088867188)"
ButtonHovered = "rgba(25, 25, 25, 1.0)"
ButtonActive = "rgba(255, 59, 59, 1.0)"
Header = "rgba(0, 0, 0, 0.454935610294342)"
HeaderHovered = "rgba(46, 46, 46, 0.800000011920929)"
HeaderActive = "rgba(249, 66, 66, 1.0)"
Separator = "rgba(0, 0, 0, 0.5)"
SeparatorHovered = "rgba(25, 102, 191, 0.7799999713897705)"
SeparatorActive = "rgba(25, 102, 191, 1.0)"
ResizeGrip = "rgba(66, 150, 249, 0.2000000029802322)"
ResizeGripHovered = "rgba(66, 150, 249, 0.6700000166893005)"
ResizeGripActive = "rgba(66, 150, 249, 0.949999988079071)"
Tab = "rgba(27, 27, 27, 1.0)"
TabHovered = "rgba(255, 93, 172, 0.800000011920929)"
TabActive = "rgba(255, 57, 57, 1.0)"
TabUnfocused = "rgba(28, 43, 61, 0.9724000096321106)"
TabUnfocusedActive = "rgba(34, 66, 108, 1.0)"
PlotLines = "rgba(255, 255, 255, 1.0)"
PlotLinesHovered = "rgba(255, 109, 89, 1.0)"
PlotHistogram = "rgba(255, 55, 55, 1.0)"
PlotHistogramHovered = "rgba(255, 55, 178, 1.0)"
TableHeaderBg = "rgba(255, 60, 60, 1.0)"
TableBorderStrong = "rgba(255, 81, 81, 1.0)"
TableBorderLight = "rgba(255, 144, 144, 0.3690987229347229)"
TableRowBg = "rgba(185, 86, 255, 0.0)"
TableRowBgAlt = "rgba(255, 70, 70, 0.1115880012512207)"
TextSelectedBg = "rgba(249, 66, 66, 1.0)"
DragDropTarget = "rgba(255, 255, 0, 0.8999999761581421)"
NavHighlight = "rgba(0, 0, 0, 0.6437768340110779)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.4678111672401428)"
NavWindowingDimBg = "rgba(0, 0, 0, 0.733905553817749)"
ModalWindowDimBg = "rgba(0, 0, 0, 0.7982832789421082)"

**Comment by Patitotective** [comment]
Hi, thanks for contributing.
Next time make sure to create a pull request as it's written on [the README](https://github.com/Patitotective/ImThemes?tab=readme-ov-file#publish-your-theme).
