### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by ConnorPaster** [Patitotective/ImThemes#37]
wen i run the exe it the gui dose not load

**Comment by Patitotective** [comment]
Hi. Can you run the exe from the command line and send the output here? Or did you close #36 because it is already solved?

**Comment by ConnorPaster** [comment]
it did not work

**Comment by Patitotective** [comment]
Can you run the exe from the terminal so I can see what's wrong? You can also try to delete the "ImThemes" folder inside "C:\Users\User\AppData\Local"

**Comment by ConnorPaster** [comment]
that fixed it ty
