### ISSUE TITLE
[Bug] Null clipboard string

### ISSUE THREAD

**Issue by BttrDrgn** [Patitotective/ImThemes#9]
Using v0.2.4 (but the zip is labeled as v0.2.3 so whichever version this actually is)

Consistently when I alt-tab multiple times, especially when a text input is active, I get crashes from the input handler. 
I also noticed this issue happens whenever the window is idle for too long. I do not have an exact time measurement but it has happened twice whenever I went away from the keyboard.

![image](https://user-images.githubusercontent.com/49764143/193462408-0a88fbdf-193b-4670-b8c1-5eb0fd2b9274.png)

**Comment by Patitotective** [comment]
Thanks for reporting it.
Could you try to reproduce the bug in this build https://github.com/Patitotective/ImThemes/suites/8574500998/artifacts/383713400.

**Comment by BttrDrgn** [comment]
I could not reproduce the alt-tabbing issue after updating , however, I will keep it running in the background and report back if I have another crash from being idle, so I won't close it after this comment. Thank you for fixing that so quickly!

**Comment by Patitotective** [comment]
Officially fixed in https://github.com/Patitotective/ImThemes/releases/tag/0.2.5.
